miesiace = (m for m in ["styczen", "luty", "marzec", "kwiecien", "maj", "czerwiec", "lipiec", "sierpien", "wrzesien", "pazdziernik", "listopad", "grudzien"])
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))
print(next(miesiace))